version: '2.1'
services:
  grafana:
    image: grafana/grafana
    network_mode: "host"
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   network_mode: "host"
