version: '2.1'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 8085:3306
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
